// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzRJApReFrVowDEbu0NaoNvVgiQZO6_cY',
    appId: '1:220330421701:web:6a746eb0b188aad8e36fac',
    messagingSenderId: '220330421701',
    projectId: 'app-flutter-fe3ac',
    authDomain: 'app-flutter-fe3ac.firebaseapp.com',
    storageBucket: 'app-flutter-fe3ac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu5pfZnxVfWIHvSq_oYZue0wmB1gLOQl0',
    appId: '1:220330421701:android:312520b5b5fd8714e36fac',
    messagingSenderId: '220330421701',
    projectId: 'app-flutter-fe3ac',
    storageBucket: 'app-flutter-fe3ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeflPCb-UD650RShOhMfBW1euT9mLiszY',
    appId: '1:220330421701:ios:54458a00c077d31ce36fac',
    messagingSenderId: '220330421701',
    projectId: 'app-flutter-fe3ac',
    storageBucket: 'app-flutter-fe3ac.firebasestorage.app',
    iosBundleId: 'com.example.appFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeflPCb-UD650RShOhMfBW1euT9mLiszY',
    appId: '1:220330421701:ios:54458a00c077d31ce36fac',
    messagingSenderId: '220330421701',
    projectId: 'app-flutter-fe3ac',
    storageBucket: 'app-flutter-fe3ac.firebasestorage.app',
    iosBundleId: 'com.example.appFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzRJApReFrVowDEbu0NaoNvVgiQZO6_cY',
    appId: '1:220330421701:web:fbb5a8862466f40ee36fac',
    messagingSenderId: '220330421701',
    projectId: 'app-flutter-fe3ac',
    authDomain: 'app-flutter-fe3ac.firebaseapp.com',
    storageBucket: 'app-flutter-fe3ac.firebasestorage.app',
  );
}
