// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4b9nsJH6SnIRbCZDxsIU6slS6s3jUzv8',
    appId: '1:795430981816:web:155299909b47561875a44d',
    messagingSenderId: '795430981816',
    projectId: 'appselfp',
    authDomain: 'appselfp.firebaseapp.com',
    storageBucket: 'appselfp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu7OW2CEPoArH8xZ-93G3w_HZ5vN_e-mg',
    appId: '1:795430981816:android:d7b24c801098963275a44d',
    messagingSenderId: '795430981816',
    projectId: 'appselfp',
    storageBucket: 'appselfp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVLAJDfUQxeKhy3zJ2fqnD7YyzXqYyR0I',
    appId: '1:795430981816:ios:0b964ee1bb8c38ac75a44d',
    messagingSenderId: '795430981816',
    projectId: 'appselfp',
    storageBucket: 'appselfp.firebasestorage.app',
    androidClientId: '795430981816-sa28ruj08ecv8ne6f50ltrq97gk07iih.apps.googleusercontent.com',
    iosClientId: '795430981816-ns4foi3hd37qcibgf8dbij18nkekk267.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVLAJDfUQxeKhy3zJ2fqnD7YyzXqYyR0I',
    appId: '1:795430981816:ios:0b964ee1bb8c38ac75a44d',
    messagingSenderId: '795430981816',
    projectId: 'appselfp',
    storageBucket: 'appselfp.firebasestorage.app',
    androidClientId: '795430981816-sa28ruj08ecv8ne6f50ltrq97gk07iih.apps.googleusercontent.com',
    iosClientId: '795430981816-ns4foi3hd37qcibgf8dbij18nkekk267.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4b9nsJH6SnIRbCZDxsIU6slS6s3jUzv8',
    appId: '1:795430981816:web:c65a1723b2ff0c6075a44d',
    messagingSenderId: '795430981816',
    projectId: 'appselfp',
    authDomain: 'appselfp.firebaseapp.com',
    storageBucket: 'appselfp.firebasestorage.app',
  );
}
